# **K-Means Clustering**

In [23]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
#loading datasets
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [25]:
path = "/content/drive/MyDrive/emnist-letters-test.csv"

DFPD = pd.read_csv(path)

DF0 = DFPD.to_numpy()


In [ ]:
#first tried for one iteration then extended idea to form loop for better results.

In [26]:
DF0.shape

(14799, 785)

In [27]:
DF1 = DF0[:,1:]

In [28]:
Int = [Int for Int in range(0,14800)]

In [29]:
pd.DataFrame(Int)


0
0          0
1          1
2          2
3          3
4          4
...      ...
14795  14795
14796  14796
14797  14797
14798  14798
14799  14799

[14800 rows x 1 columns]

In [30]:
n = 14799
k = 19


In [31]:
centroid = DF1[np.random.choice(Int, 19, replace = False)]
pd.DataFrame(centroid)

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  777  \
0     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
1     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
2     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
3     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
4     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
5     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
6     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
7     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
8     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
9     0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
10    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
11    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
12    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
13    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
14    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
15    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
16    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
17    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   
18    0    0    0    0    0    0    0    0    0    0  ...    0    0    0    0   

    778  779  780  781  782  783  
0     0    0    0    0    0    0  
1     0    0    0    0    0    0  
2     0    0    0    0    0    0  
3     0    0    0    0    0    0  
4     0    0    0    0    0    0  
5     0    0    0    0    0    0  
6     0    0    0    0    0    0  
7     0    0    0    0    0    0  
8     0    0    0    0    0    0  
9     0    0    0    0    0    0  
10    0    0    0    0    0    0  
11    0    0    0    0    0    0  
12    0    0    0    0    0    0  
13    0    0    0    0    0    0  
14    0    0    0    0    0    0  
15    0    0    0    0    0    0  
16    0    0    0    0    0    0  
17    0    0    0    0    0    0  
18    0    0    0    0    0    0  

[19 rows x 784 columns]

In [32]:
centroid.shape
DF1.shape

(14799, 784)

In [33]:
euc_list = []

for i in range(19):
  euc_dist = 0
  euc_dist = np.sqrt(np.sum(((DF1 - centroid[i])**2), axis=1)) 
  
  euc_list.append(euc_dist)

  

pd.DataFrame(euc_list)

0            1            2            3            4      \
0   3235.123027  2827.754586  3192.448120  3088.728541  3045.985226   
1   2965.662321  3002.376059  3248.841794  2778.632397  3065.624569   
2   2902.662915  3233.890691  3224.168730  3259.120280  2927.065254   
3   3277.571357  2826.361442  2964.931365  3275.891482  3054.436609   
4   3172.036412  2749.976727  3276.430832  2565.814101  2940.167342   
5   3211.164586  2568.588912  3043.889617  2712.468433  2598.349284   
6   3045.227085  2681.164486  3227.569364  2491.938402  3215.283658   
7   3065.685242  3088.827447  3050.523889  2907.641140  3475.298117   
8   2908.071182  3107.972812  3516.789445  2490.918104  3038.512630   
9   3063.491635  2359.753801  2430.978198  2797.741589  3071.257397   
10  2594.429417  2887.140627  3201.282243  2918.511778  3381.537964   
11  3210.774517  3067.468337  3016.677477  2774.381012  2891.329106   
12  2810.013167  2738.235746  3068.198494  2719.159613  3220.750378   
13  2883.872570  2886.963803  3328.680069  3133.382517  2865.994766   
14  2893.491835  2601.900075  3021.786392  2738.323940  3100.509958   
15  3372.829673  2796.954236  3078.288810  2743.402085  2540.229320   
16  3223.851578  3004.948585  3253.402680  2919.554418  3042.877257   
17  2963.599501  2660.249424  3273.400067  2724.440677  3340.257026   
18  3078.865700  2778.323775  3098.368280  2708.359097  2399.488487   

          5            6            7            8            9      ...  \
0   3080.353389  3200.397632  3010.504609  3221.123872  3321.179459  ...   
1   3060.111599  3009.371529  3026.649633  3326.144765  3252.623095  ...   
2   3116.151793  3348.778285  3482.982486  2965.804107  2639.955681  ...   
3   2894.176912  3209.588136  3397.181920  3278.712552  2942.907406  ...   
4   2871.158825  3035.051070  2927.723006  3278.440330  2986.529591  ...   
5   2947.443977  3130.800217  3055.037643  3176.532701  3180.802100  ...   
6   2747.192385  2762.429004  2569.322284  3265.987753  2854.920664  ...   
7   3127.135430  3198.307052  3322.135608  3462.463285  3088.682567  ...   
8   2671.412735  2676.659485  2722.806089  2971.111240  2911.196661  ...   
9   2804.193467  2866.404193  2782.064341  3536.524424  3035.175942  ...   
10  2792.273626  2959.903039  2899.957069  3471.370911  3007.671192  ...   
11  3072.067219  3252.652302  3239.382040  3276.869085  2846.431274  ...   
12  2948.620694  2976.007728  3040.215617  3297.982717  3037.014323  ...   
13  2969.998485  2949.267197  2953.558532  3132.954676  2917.773295  ...   
14  2916.695905  3131.830615  3239.059431  3053.125775  2883.758138  ...   
15  2353.782913  2721.828797  3013.704199  2998.033355  2738.173479  ...   
16  2977.973976  3191.776778  3170.957899  3328.295510  3065.072756  ...   
17  2683.849847  2601.582211  2559.060179  3451.575003  2761.755963  ...   
18  2599.631512  3137.278120  2951.235504  2629.834215  2866.476932  ...   

          14789        14790        14791        14792        14793  \
0   3173.942501  3160.120093  3058.021746  2986.266231  3098.036959   
1   2642.109952  3084.761093  2632.946069  2590.776718  2652.375728   
2   2602.504563  2956.596692  3038.576970  3063.581074  2388.063651   
3   2932.885610  2848.806066  2510.092030  2990.577703  2703.939718   
4   2625.433107  2738.539209  2970.626702  2666.055888  3036.472460   
5   3136.809526  3018.555615  2748.286375  3131.711513  3497.765572   
6   2550.750086  2677.604153  2999.586305  2432.758311  3079.278812   
7   2354.846492  2974.155342  2938.350217  2770.656420  2669.700358   
8   2824.943893  2907.272949  2918.825449  2362.186910  2797.783408   
9   2629.408869  2674.795506  2903.780123  2806.555896  2949.168527   
10  2518.509877  2587.957109  2807.967236  2266.293670  2459.473927   
11  2838.279937  3171.349397  2929.777978  3165.271868  3341.017061   
12  2653.845512  2610.618318  2591.056927  2389.462910  2528.132908   
13  2687.219195  2702.651106  2916.431895  2440.406933  2444.161410   
14 

In [34]:
closest = np.argmin(euc_list, axis = 0)

In [35]:
np.reshape(closest, (14799,1))

array([[10],
       [ 9],
       [ 9],
       ...,
       [14],
       [ 7],
       [18]])

In [36]:
pd.DataFrame(closest)

0
0      10
1       9
2       9
3       8
4      18
...    ..
14794  14
14795  12
14796  14
14797   7
14798  18

[14799 rows x 1 columns]

In [37]:
arr = DF1[np.where(closest == 0)]

In [38]:
cen = np.mean(arr, axis =0)

In [39]:
cen.tolist()

[0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.01556420233463035,
 0.023346303501945526,
 0.038910505836575876,
 0.07003891050583658,
 0.06614785992217899,
 0.0622568093385214,
 0.01556420233463035,
 0.0311284046692607,
 0.08560311284046693,
 0.11284046692607004,
 0.14396887159533073,
 0.0933852140077821,
 0.1828793774319066,
 0.245136186770428,
 0.24124513618677043,
 0.19844357976653695,
 0.17120622568093385,
 0.13618677042801555,
 0.19066147859922178,
 0.10894941634241245,
 0.03501945525291829,
 0.01556420233463035,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.08560311284046693,
 0.8132295719844358,
 1.377431906614786,
 3.2490272373540856,
 3.964980544747082,
 3.735408560311284,
 4.533073929961089,
 3.431906614785992,
 4.116731517509727,
 5.443579766536965,
 7.739299610894942,
 9.167315175097276,
 8.988326848249027,
 9.038910505836576,
 8.517509727626459,


In [40]:
def Kmeans_model(DF1, k, s):
  Int = [Int for Int in range(0,14800)]
  centroid = DF1[np.random.choice(Int, k, replace = False)]  
  for t in range(s):
    euc_list = []
  
    for i in range(k):
     euc_dist = 0
     euc_dist = np.sqrt(np.sum(((DF1 - centroid[i])**2), axis=1)) 
     euc_list.append(euc_dist)

    closest = np.argmin(euc_list, axis = 0) 
    centroidu = np.empty_like(centroid) 
    for j in range(k):
      arr = DF1[np.where(closest == j)]
      cen = 0
      cen = np.mean(arr, axis =0)
      centroidu[j] = cen
    
    if centroid.all == centroidu.all:
      break
    
    
    print(closest)
    
  centroid = centroidu
  return closest  

# Clusters

In [41]:
A = Kmeans_model(DF1, 19, 100) 

[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6 10 10]
[18  7  7 ...  6

In [42]:
pd.DataFrame(A)

0
0      18
1       7
2       7
3      17
4       6
...    ..
14794   7
14795  15
14796   6
14797  10
14798  10

[14799 rows x 1 columns]

In [43]:
if A[0] == A[1]:
  print(0)

In [44]:
if A[0] != A[1]:
  print(1)

1


In [48]:
A.tolist()

[18,
 7,
 7,
 17,
 6,
 17,
 12,
 15,
 3,
 10,
 17,
 7,
 5,
 6,
 11,
 12,
 3,
 12,
 13,
 11,
 12,
 12,
 12,
 5,
 14,
 2,
 11,
 3,
 7,
 9,
 6,
 10,
 9,
 10,
 7,
 9,
 18,
 3,
 11,
 10,
 7,
 7,
 5,
 7,
 11,
 14,
 7,
 12,
 3,
 11,
 7,
 13,
 11,
 7,
 3,
 3,
 2,
 12,
 14,
 5,
 2,
 14,
 7,
 11,
 9,
 6,
 6,
 8,
 6,
 5,
 2,
 9,
 7,
 16,
 14,
 13,
 3,
 13,
 2,
 7,
 5,
 5,
 7,
 12,
 6,
 7,
 14,
 5,
 9,
 7,
 11,
 17,
 7,
 16,
 5,
 7,
 14,
 5,
 9,
 3,
 6,
 3,
 2,
 11,
 5,
 14,
 6,
 2,
 2,
 9,
 14,
 6,
 6,
 7,
 13,
 7,
 7,
 13,
 13,
 7,
 5,
 6,
 4,
 6,
 2,
 5,
 17,
 7,
 4,
 18,
 13,
 13,
 12,
 11,
 12,
 2,
 3,
 9,
 6,
 7,
 2,
 12,
 5,
 6,
 12,
 2,
 7,
 6,
 18,
 5,
 3,
 7,
 5,
 7,
 7,
 7,
 18,
 4,
 13,
 18,
 6,
 13,
 7,
 10,
 17,
 6,
 7,
 17,
 2,
 8,
 11,
 9,
 6,
 5,
 10,
 9,
 5,
 13,
 7,
 5,
 12,
 17,
 6,
 3,
 11,
 6,
 2,
 6,
 5,
 10,
 12,
 12,
 9,
 9,
 6,
 2,
 2,
 2,
 11,
 16,
 16,
 6,
 2,
 14,
 9,
 7,
 5,
 5,
 12,
 7,
 17,
 5,
 7,
 17,
 2,
 11,
 9,
 13,
 11,
 2,
 2,
 7,
 2,
 18,
 6,
 2,
 9,
 2,
 9,