## **K-Nearest Neighbour**



In [ ]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#loading datasets
from google.colab import drive
drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
path2 = "/content/drive/MyDrive/emnist-letters-test.csv"
path1 = "/content/drive/MyDrive/emnist-letters-train.csv"

Train0 = pd.read_csv(path1, header = None)
Train1 = Train0.to_numpy()

Test0 = pd.read_csv(path2, header = None)
Test1 = Test0.to_numpy()

In [ ]:
Train1.shape

(88800, 785)

In [ ]:
Test1.shape

(14800, 785)

In [ ]:
X_train_unscaled = Train1[:,1:]

In [ ]:
X_test_unscaled = Test1[:,1:]

In [ ]:
def feature_scaling(A) : 
  return np.divide(A, 256)

In [ ]:
X_Train1 = feature_scaling(X_train_unscaled)

In [ ]:
X_Test1 = feature_scaling(X_test_unscaled)

In [ ]:
Y_train = np.reshape(Train1[:,0],(88800,1))
Y_train.shape

(88800, 1)

In [ ]:
pd.DataFrame(Y_train)

0
0      23
1       7
2      16
3      15
4      23
...    ..
88795   1
88796  21
88797   1
88798  23
88799  12

[88800 rows x 1 columns]

# Model

In [ ]:
def KNN(test_case, X, test, Y):
  euc_list = []
  for i in range(test_case):
    euc_dist = 0
    euc_dist = np.sqrt(np.sum(((X - Y[i])**2), axis=1))
    euc_list.append(euc_dist)
  euc = np.array(euc_list)

  
  arg1 = []
  for i in range(test_case):
    b = 0
    b = np.argpartition(euc[i], 26)
    arg1.append(b)
  argf = np.array(arg1)

  argf1 = argf[:, 0:26]
  
  pred = np.zeros((argf1.shape[0], argf1.shape[1]))
  for i in range(argf1.shape[0]):
    for j in range(argf1.shape[1]):
      pred[i,j] = Y[argf1[i,j], 0]






  '''index_list = []
  for i in range(test_case):
     index = 0
     index = np.where(np.sort(euc[i]))
     index_list.append(index)
  euc1 = np.concatenate((index, euc), axis = 0)

  for i in range(test_case):
    t = 0
    s = euc1[0]
    t = euc1[i]
    a = np.concatenate([s,t], axis = 0)
   ''' 

    

  return pred
   

In [ ]:
A = KNN(1000, X_Train1, X_Test1, Y_train)

In [ ]:
A.shape

(1000, 26)

In [ ]:
A

array([[ 1.,  7.,  2., ...,  5., 15., 15.],
       [ 5., 13., 14., ..., 26., 11.,  7.],
       [ 5.,  5.,  1., ...,  5.,  5., 15.],
       ...,
       [ 7.,  1.,  7., ..., 15., 14., 15.],
       [ 7.,  7., 26., ..., 19.,  1.,  7.],
       [ 2., 26.,  1., ...,  7., 14., 15.]])

In [ ]:
B = A.tolist()

In [ ]:
len(B[0])

26

In [ ]:
D = []
for i in range(len(B)):
  c = max(B[i],key=B[i].count)
  D.append(c)
E = np.array(D)
E

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 1., 1., 1., 1., 1., 1., 1., 1., 5., 1., 1., 5., 1.,
       1., 5., 1., 1., 5., 1., 1., 1., 1., 1., 5., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 5., 1., 1., 1., 1., 1., 1., 1., 5.,
       5., 5., 5., 5., 5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 5., 1., 1., 1., 1., 1.,
       1., 1., 1., 5., 1., 1., 1., 5., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 5., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 5., 1., 1., 1., 1., 5., 1., 1., 1., 1.,
       1., 1., 1., 5., 1.

In [ ]:
y = Test1[0:1000, 0]
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [ ]:
final = y-E

In [ ]:
count = 0 
for i in range(1000):
    if final[i] == 0:
        count+=1


In [ ]:
count

736

# Accuracy

In [ ]:
count/10

73.6